/* automatically generated by rust-bindgen */

use crate::webgpu::*;

#[repr(C)]
pub struct DawnProcTable {
    pub getProcAddress: WGPUProcGetProcAddress,
    pub createInstance: WGPUProcCreateInstance,
    pub bindGroupReference: WGPUProcBindGroupReference,
    pub bindGroupRelease: WGPUProcBindGroupRelease,
    pub bindGroupLayoutReference: WGPUProcBindGroupLayoutReference,
    pub bindGroupLayoutRelease: WGPUProcBindGroupLayoutRelease,
    pub bufferDestroy: WGPUProcBufferDestroy,
    pub bufferMapReadAsync: WGPUProcBufferMapReadAsync,
    pub bufferMapWriteAsync: WGPUProcBufferMapWriteAsync,
    pub bufferSetSubData: WGPUProcBufferSetSubData,
    pub bufferUnmap: WGPUProcBufferUnmap,
    pub bufferReference: WGPUProcBufferReference,
    pub bufferRelease: WGPUProcBufferRelease,
    pub commandBufferReference: WGPUProcCommandBufferReference,
    pub commandBufferRelease: WGPUProcCommandBufferRelease,
    pub commandEncoderBeginComputePass: WGPUProcCommandEncoderBeginComputePass,
    pub commandEncoderBeginRenderPass: WGPUProcCommandEncoderBeginRenderPass,
    pub commandEncoderCopyBufferToBuffer: WGPUProcCommandEncoderCopyBufferToBuffer,
    pub commandEncoderCopyBufferToTexture: WGPUProcCommandEncoderCopyBufferToTexture,
    pub commandEncoderCopyTextureToBuffer: WGPUProcCommandEncoderCopyTextureToBuffer,
    pub commandEncoderCopyTextureToTexture: WGPUProcCommandEncoderCopyTextureToTexture,
    pub commandEncoderFinish: WGPUProcCommandEncoderFinish,
    pub commandEncoderInsertDebugMarker: WGPUProcCommandEncoderInsertDebugMarker,
    pub commandEncoderPopDebugGroup: WGPUProcCommandEncoderPopDebugGroup,
    pub commandEncoderPushDebugGroup: WGPUProcCommandEncoderPushDebugGroup,
    pub commandEncoderReference: WGPUProcCommandEncoderReference,
    pub commandEncoderRelease: WGPUProcCommandEncoderRelease,
    pub computePassEncoderDispatch: WGPUProcComputePassEncoderDispatch,
    pub computePassEncoderDispatchIndirect: WGPUProcComputePassEncoderDispatchIndirect,
    pub computePassEncoderEndPass: WGPUProcComputePassEncoderEndPass,
    pub computePassEncoderInsertDebugMarker: WGPUProcComputePassEncoderInsertDebugMarker,
    pub computePassEncoderPopDebugGroup: WGPUProcComputePassEncoderPopDebugGroup,
    pub computePassEncoderPushDebugGroup: WGPUProcComputePassEncoderPushDebugGroup,
    pub computePassEncoderSetBindGroup: WGPUProcComputePassEncoderSetBindGroup,
    pub computePassEncoderSetPipeline: WGPUProcComputePassEncoderSetPipeline,
    pub computePassEncoderReference: WGPUProcComputePassEncoderReference,
    pub computePassEncoderRelease: WGPUProcComputePassEncoderRelease,
    pub computePipelineGetBindGroupLayout: WGPUProcComputePipelineGetBindGroupLayout,
    pub computePipelineReference: WGPUProcComputePipelineReference,
    pub computePipelineRelease: WGPUProcComputePipelineRelease,
    pub deviceCreateBindGroup: WGPUProcDeviceCreateBindGroup,
    pub deviceCreateBindGroupLayout: WGPUProcDeviceCreateBindGroupLayout,
    pub deviceCreateBuffer: WGPUProcDeviceCreateBuffer,
    pub deviceCreateBufferMapped: WGPUProcDeviceCreateBufferMapped,
    pub deviceCreateBufferMappedAsync: WGPUProcDeviceCreateBufferMappedAsync,
    pub deviceCreateCommandEncoder: WGPUProcDeviceCreateCommandEncoder,
    pub deviceCreateComputePipeline: WGPUProcDeviceCreateComputePipeline,
    pub deviceCreatePipelineLayout: WGPUProcDeviceCreatePipelineLayout,
    pub deviceCreateQueue: WGPUProcDeviceCreateQueue,
    pub deviceCreateRenderBundleEncoder: WGPUProcDeviceCreateRenderBundleEncoder,
    pub deviceCreateRenderPipeline: WGPUProcDeviceCreateRenderPipeline,
    pub deviceCreateSampler: WGPUProcDeviceCreateSampler,
    pub deviceCreateShaderModule: WGPUProcDeviceCreateShaderModule,
    pub deviceCreateSwapChain: WGPUProcDeviceCreateSwapChain,
    pub deviceCreateTexture: WGPUProcDeviceCreateTexture,
    pub deviceInjectError: WGPUProcDeviceInjectError,
    pub deviceLoseForTesting: WGPUProcDeviceLoseForTesting,
    pub devicePopErrorScope: WGPUProcDevicePopErrorScope,
    pub devicePushErrorScope: WGPUProcDevicePushErrorScope,
    pub deviceSetDeviceLostCallback: WGPUProcDeviceSetDeviceLostCallback,
    pub deviceSetUncapturedErrorCallback: WGPUProcDeviceSetUncapturedErrorCallback,
    pub deviceTick: WGPUProcDeviceTick,
    pub deviceReference: WGPUProcDeviceReference,
    pub deviceRelease: WGPUProcDeviceRelease,
    pub fenceGetCompletedValue: WGPUProcFenceGetCompletedValue,
    pub fenceOnCompletion: WGPUProcFenceOnCompletion,
    pub fenceReference: WGPUProcFenceReference,
    pub fenceRelease: WGPUProcFenceRelease,
    pub instanceCreateSurface: WGPUProcInstanceCreateSurface,
    pub instanceReference: WGPUProcInstanceReference,
    pub instanceRelease: WGPUProcInstanceRelease,
    pub pipelineLayoutReference: WGPUProcPipelineLayoutReference,
    pub pipelineLayoutRelease: WGPUProcPipelineLayoutRelease,
    pub queueCreateFence: WGPUProcQueueCreateFence,
    pub queueSignal: WGPUProcQueueSignal,
    pub queueSubmit: WGPUProcQueueSubmit,
    pub queueReference: WGPUProcQueueReference,
    pub queueRelease: WGPUProcQueueRelease,
    pub renderBundleReference: WGPUProcRenderBundleReference,
    pub renderBundleRelease: WGPUProcRenderBundleRelease,
    pub renderBundleEncoderDraw: WGPUProcRenderBundleEncoderDraw,
    pub renderBundleEncoderDrawIndexed: WGPUProcRenderBundleEncoderDrawIndexed,
    pub renderBundleEncoderDrawIndexedIndirect: WGPUProcRenderBundleEncoderDrawIndexedIndirect,
    pub renderBundleEncoderDrawIndirect: WGPUProcRenderBundleEncoderDrawIndirect,
    pub renderBundleEncoderFinish: WGPUProcRenderBundleEncoderFinish,
    pub renderBundleEncoderInsertDebugMarker: WGPUProcRenderBundleEncoderInsertDebugMarker,
    pub renderBundleEncoderPopDebugGroup: WGPUProcRenderBundleEncoderPopDebugGroup,
    pub renderBundleEncoderPushDebugGroup: WGPUProcRenderBundleEncoderPushDebugGroup,
    pub renderBundleEncoderSetBindGroup: WGPUProcRenderBundleEncoderSetBindGroup,
    pub renderBundleEncoderSetIndexBuffer: WGPUProcRenderBundleEncoderSetIndexBuffer,
    pub renderBundleEncoderSetPipeline: WGPUProcRenderBundleEncoderSetPipeline,
    pub renderBundleEncoderSetVertexBuffer: WGPUProcRenderBundleEncoderSetVertexBuffer,
    pub renderBundleEncoderReference: WGPUProcRenderBundleEncoderReference,
    pub renderBundleEncoderRelease: WGPUProcRenderBundleEncoderRelease,
    pub renderPassEncoderDraw: WGPUProcRenderPassEncoderDraw,
    pub renderPassEncoderDrawIndexed: WGPUProcRenderPassEncoderDrawIndexed,
    pub renderPassEncoderDrawIndexedIndirect: WGPUProcRenderPassEncoderDrawIndexedIndirect,
    pub renderPassEncoderDrawIndirect: WGPUProcRenderPassEncoderDrawIndirect,
    pub renderPassEncoderEndPass: WGPUProcRenderPassEncoderEndPass,
    pub renderPassEncoderExecuteBundles: WGPUProcRenderPassEncoderExecuteBundles,
    pub renderPassEncoderInsertDebugMarker: WGPUProcRenderPassEncoderInsertDebugMarker,
    pub renderPassEncoderPopDebugGroup: WGPUProcRenderPassEncoderPopDebugGroup,
    pub renderPassEncoderPushDebugGroup: WGPUProcRenderPassEncoderPushDebugGroup,
    pub renderPassEncoderSetBindGroup: WGPUProcRenderPassEncoderSetBindGroup,
    pub renderPassEncoderSetBlendColor: WGPUProcRenderPassEncoderSetBlendColor,
    pub renderPassEncoderSetIndexBuffer: WGPUProcRenderPassEncoderSetIndexBuffer,
    pub renderPassEncoderSetPipeline: WGPUProcRenderPassEncoderSetPipeline,
    pub renderPassEncoderSetScissorRect: WGPUProcRenderPassEncoderSetScissorRect,
    pub renderPassEncoderSetStencilReference: WGPUProcRenderPassEncoderSetStencilReference,
    pub renderPassEncoderSetVertexBuffer: WGPUProcRenderPassEncoderSetVertexBuffer,
    pub renderPassEncoderSetViewport: WGPUProcRenderPassEncoderSetViewport,
    pub renderPassEncoderReference: WGPUProcRenderPassEncoderReference,
    pub renderPassEncoderRelease: WGPUProcRenderPassEncoderRelease,
    pub renderPipelineGetBindGroupLayout: WGPUProcRenderPipelineGetBindGroupLayout,
    pub renderPipelineReference: WGPUProcRenderPipelineReference,
    pub renderPipelineRelease: WGPUProcRenderPipelineRelease,
    pub samplerReference: WGPUProcSamplerReference,
    pub samplerRelease: WGPUProcSamplerRelease,
    pub shaderModuleReference: WGPUProcShaderModuleReference,
    pub shaderModuleRelease: WGPUProcShaderModuleRelease,
    pub surfaceReference: WGPUProcSurfaceReference,
    pub surfaceRelease: WGPUProcSurfaceRelease,
    pub swapChainConfigure: WGPUProcSwapChainConfigure,
    pub swapChainGetCurrentTextureView: WGPUProcSwapChainGetCurrentTextureView,
    pub swapChainPresent: WGPUProcSwapChainPresent,
    pub swapChainReference: WGPUProcSwapChainReference,
    pub swapChainRelease: WGPUProcSwapChainRelease,
    pub textureCreateView: WGPUProcTextureCreateView,
    pub textureDestroy: WGPUProcTextureDestroy,
    pub textureReference: WGPUProcTextureReference,
    pub textureRelease: WGPUProcTextureRelease,
    pub textureViewReference: WGPUProcTextureViewReference,
    pub textureViewRelease: WGPUProcTextureViewRelease,
}
#[test]
fn bindgen_test_layout_DawnProcTable() {
    assert_eq!(
        ::core::mem::size_of::<DawnProcTable>(),
        1064usize,
        concat!("Size of: ", stringify!(DawnProcTable))
    );
    assert_eq!(
        ::core::mem::align_of::<DawnProcTable>(),
        8usize,
        concat!("Alignment of ", stringify!(DawnProcTable))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).getProcAddress as *const _ as usize },
        0usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(getProcAddress)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).createInstance as *const _ as usize },
        8usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(createInstance)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).bindGroupReference as *const _ as usize
        },
        16usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bindGroupReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bindGroupRelease as *const _ as usize },
        24usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bindGroupRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).bindGroupLayoutReference as *const _ as usize
        },
        32usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bindGroupLayoutReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).bindGroupLayoutRelease as *const _ as usize
        },
        40usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bindGroupLayoutRelease)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bufferDestroy as *const _ as usize },
        48usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferDestroy)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).bufferMapReadAsync as *const _ as usize
        },
        56usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferMapReadAsync)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).bufferMapWriteAsync as *const _ as usize
        },
        64usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferMapWriteAsync)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bufferSetSubData as *const _ as usize },
        72usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferSetSubData)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bufferUnmap as *const _ as usize },
        80usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferUnmap)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bufferReference as *const _ as usize },
        88usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).bufferRelease as *const _ as usize },
        96usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(bufferRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandBufferReference as *const _ as usize
        },
        104usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandBufferReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandBufferRelease as *const _ as usize
        },
        112usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandBufferRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderBeginComputePass as *const _
                as usize
        },
        120usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderBeginComputePass)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderBeginRenderPass as *const _
                as usize
        },
        128usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderBeginRenderPass)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderCopyBufferToBuffer as *const _
                as usize
        },
        136usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderCopyBufferToBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderCopyBufferToTexture as *const _
                as usize
        },
        144usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderCopyBufferToTexture)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderCopyTextureToBuffer as *const _
                as usize
        },
        152usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderCopyTextureToBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderCopyTextureToTexture
                as *const _ as usize
        },
        160usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderCopyTextureToTexture)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderFinish as *const _ as usize
        },
        168usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderFinish)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderInsertDebugMarker as *const _
                as usize
        },
        176usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderInsertDebugMarker)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderPopDebugGroup as *const _
                as usize
        },
        184usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderPopDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderPushDebugGroup as *const _
                as usize
        },
        192usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderPushDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderReference as *const _ as usize
        },
        200usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).commandEncoderRelease as *const _ as usize
        },
        208usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(commandEncoderRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderDispatch as *const _
                as usize
        },
        216usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderDispatch)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderDispatchIndirect
                as *const _ as usize
        },
        224usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderDispatchIndirect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderEndPass as *const _
                as usize
        },
        232usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderEndPass)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderInsertDebugMarker
                as *const _ as usize
        },
        240usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderInsertDebugMarker)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderPopDebugGroup as *const _
                as usize
        },
        248usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderPopDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderPushDebugGroup as *const _
                as usize
        },
        256usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderPushDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderSetBindGroup as *const _
                as usize
        },
        264usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderSetBindGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderSetPipeline as *const _
                as usize
        },
        272usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderSetPipeline)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderReference as *const _
                as usize
        },
        280usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePassEncoderRelease as *const _
                as usize
        },
        288usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePassEncoderRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePipelineGetBindGroupLayout as *const _
                as usize
        },
        296usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePipelineGetBindGroupLayout)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePipelineReference as *const _ as usize
        },
        304usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePipelineReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).computePipelineRelease as *const _ as usize
        },
        312usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(computePipelineRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateBindGroup as *const _ as usize
        },
        320usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateBindGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateBindGroupLayout as *const _
                as usize
        },
        328usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateBindGroupLayout)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateBuffer as *const _ as usize
        },
        336usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateBufferMapped as *const _ as usize
        },
        344usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateBufferMapped)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateBufferMappedAsync as *const _
                as usize
        },
        352usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateBufferMappedAsync)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateCommandEncoder as *const _
                as usize
        },
        360usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateCommandEncoder)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateComputePipeline as *const _
                as usize
        },
        368usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateComputePipeline)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreatePipelineLayout as *const _
                as usize
        },
        376usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreatePipelineLayout)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateQueue as *const _ as usize
        },
        384usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateQueue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateRenderBundleEncoder as *const _
                as usize
        },
        392usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateRenderBundleEncoder)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateRenderPipeline as *const _
                as usize
        },
        400usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateRenderPipeline)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateSampler as *const _ as usize
        },
        408usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateSampler)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateShaderModule as *const _ as usize
        },
        416usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateShaderModule)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateSwapChain as *const _ as usize
        },
        424usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateSwapChain)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceCreateTexture as *const _ as usize
        },
        432usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceCreateTexture)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceInjectError as *const _ as usize
        },
        440usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceInjectError)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceLoseForTesting as *const _ as usize
        },
        448usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceLoseForTesting)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).devicePopErrorScope as *const _ as usize
        },
        456usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(devicePopErrorScope)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).devicePushErrorScope as *const _ as usize
        },
        464usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(devicePushErrorScope)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceSetDeviceLostCallback as *const _
                as usize
        },
        472usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceSetDeviceLostCallback)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).deviceSetUncapturedErrorCallback as *const _
                as usize
        },
        480usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceSetUncapturedErrorCallback)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).deviceTick as *const _ as usize },
        488usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceTick)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).deviceReference as *const _ as usize },
        496usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).deviceRelease as *const _ as usize },
        504usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(deviceRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).fenceGetCompletedValue as *const _ as usize
        },
        512usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(fenceGetCompletedValue)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).fenceOnCompletion as *const _ as usize
        },
        520usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(fenceOnCompletion)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).fenceReference as *const _ as usize },
        528usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(fenceReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).fenceRelease as *const _ as usize },
        536usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(fenceRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).instanceCreateSurface as *const _ as usize
        },
        544usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(instanceCreateSurface)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).instanceReference as *const _ as usize
        },
        552usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(instanceReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).instanceRelease as *const _ as usize },
        560usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(instanceRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).pipelineLayoutReference as *const _ as usize
        },
        568usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(pipelineLayoutReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).pipelineLayoutRelease as *const _ as usize
        },
        576usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(pipelineLayoutRelease)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).queueCreateFence as *const _ as usize },
        584usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(queueCreateFence)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).queueSignal as *const _ as usize },
        592usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(queueSignal)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).queueSubmit as *const _ as usize },
        600usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(queueSubmit)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).queueReference as *const _ as usize },
        608usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(queueReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).queueRelease as *const _ as usize },
        616usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(queueRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleReference as *const _ as usize
        },
        624usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleRelease as *const _ as usize
        },
        632usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderDraw as *const _ as usize
        },
        640usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderDraw)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderDrawIndexed as *const _
                as usize
        },
        648usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderDrawIndexed)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderDrawIndexedIndirect
                as *const _ as usize
        },
        656usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderDrawIndexedIndirect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderDrawIndirect as *const _
                as usize
        },
        664usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderDrawIndirect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderFinish as *const _
                as usize
        },
        672usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderFinish)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderInsertDebugMarker
                as *const _ as usize
        },
        680usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderInsertDebugMarker)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderPopDebugGroup as *const _
                as usize
        },
        688usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderPopDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderPushDebugGroup as *const _
                as usize
        },
        696usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderPushDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderSetBindGroup as *const _
                as usize
        },
        704usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderSetBindGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderSetIndexBuffer as *const _
                as usize
        },
        712usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderSetIndexBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderSetPipeline as *const _
                as usize
        },
        720usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderSetPipeline)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderSetVertexBuffer
                as *const _ as usize
        },
        728usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderSetVertexBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderReference as *const _
                as usize
        },
        736usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderBundleEncoderRelease as *const _
                as usize
        },
        744usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderBundleEncoderRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderDraw as *const _ as usize
        },
        752usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderDraw)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderDrawIndexed as *const _
                as usize
        },
        760usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderDrawIndexed)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderDrawIndexedIndirect
                as *const _ as usize
        },
        768usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderDrawIndexedIndirect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderDrawIndirect as *const _
                as usize
        },
        776usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderDrawIndirect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderEndPass as *const _ as usize
        },
        784usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderEndPass)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderExecuteBundles as *const _
                as usize
        },
        792usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderExecuteBundles)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderInsertDebugMarker
                as *const _ as usize
        },
        800usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderInsertDebugMarker)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderPopDebugGroup as *const _
                as usize
        },
        808usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderPopDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderPushDebugGroup as *const _
                as usize
        },
        816usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderPushDebugGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetBindGroup as *const _
                as usize
        },
        824usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetBindGroup)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetBlendColor as *const _
                as usize
        },
        832usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetBlendColor)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetIndexBuffer as *const _
                as usize
        },
        840usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetIndexBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetPipeline as *const _
                as usize
        },
        848usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetPipeline)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetScissorRect as *const _
                as usize
        },
        856usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetScissorRect)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetStencilReference
                as *const _ as usize
        },
        864usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetStencilReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetVertexBuffer as *const _
                as usize
        },
        872usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetVertexBuffer)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderSetViewport as *const _
                as usize
        },
        880usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderSetViewport)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderReference as *const _
                as usize
        },
        888usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPassEncoderRelease as *const _ as usize
        },
        896usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPassEncoderRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPipelineGetBindGroupLayout as *const _
                as usize
        },
        904usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPipelineGetBindGroupLayout)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPipelineReference as *const _ as usize
        },
        912usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPipelineReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).renderPipelineRelease as *const _ as usize
        },
        920usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(renderPipelineRelease)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).samplerReference as *const _ as usize },
        928usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(samplerReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).samplerRelease as *const _ as usize },
        936usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(samplerRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).shaderModuleReference as *const _ as usize
        },
        944usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(shaderModuleReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).shaderModuleRelease as *const _ as usize
        },
        952usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(shaderModuleRelease)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).surfaceReference as *const _ as usize },
        960usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(surfaceReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).surfaceRelease as *const _ as usize },
        968usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(surfaceRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).swapChainConfigure as *const _ as usize
        },
        976usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(swapChainConfigure)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).swapChainGetCurrentTextureView as *const _
                as usize
        },
        984usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(swapChainGetCurrentTextureView)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).swapChainPresent as *const _ as usize },
        992usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(swapChainPresent)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).swapChainReference as *const _ as usize
        },
        1000usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(swapChainReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).swapChainRelease as *const _ as usize },
        1008usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(swapChainRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).textureCreateView as *const _ as usize
        },
        1016usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureCreateView)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).textureDestroy as *const _ as usize },
        1024usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureDestroy)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).textureReference as *const _ as usize },
        1032usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureReference)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<DawnProcTable>())).textureRelease as *const _ as usize },
        1040usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureRelease)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).textureViewReference as *const _ as usize
        },
        1048usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureViewReference)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<DawnProcTable>())).textureViewRelease as *const _ as usize
        },
        1056usize,
        concat!(
        "Offset of field: ",
        stringify!(DawnProcTable),
        "::",
        stringify!(textureViewRelease)
        )
    );
}
impl ::core::fmt::Debug for DawnProcTable {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        write!(f, "DawnProcTable {{  }}")
    }
}
